# Generated by Django 2.0.2 on 2018-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Number_by_Genres',
            fields=[
                ('genres', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'total_number_by_genres',
                'managed': False,
            },
        ),
    ]
